### ISSUE TITLE
Missing tslib for node 14.x.x

### ISSUE THREAD

**Issue by gnesher** [n6ai/minze#33]
### Describe the bug

Running npm run build on a freshly installed minze project results in the following error:

`[!] (plugin typescript) Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
    at error (/Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:21891:12)
    at Object.error (/Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:22614:20)
    at preflight (/Users/guynesher/work/minze/minze-angular/node_modules/@rollup/plugin-typescript/dist/index.js:496:17)
    at Object.buildStart (/Users/guynesher/work/minze/minze-angular/node_modules/@rollup/plugin-typescript/dist/index.js:737:13)
    at /Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:22823:37
    at async Promise.all (index 1)
    at /Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:23611:13
    at catchUnfinishedHookActions (/Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:23121:20)
    at rollupInternal (/Users/guynesher/work/minze/minze-angular/node_modules/rollup/dist/shared/rollup.js:23609:5)`

### Reproduction

Error happens when using Node 14.x.x, upgrading to 16.x.x fixes the problem.
For Node 14.x.x error can be fixed by installing tslib.

I'm happy to open a PR for this, but since it only affects older node versions I wasn't sure it's needed and we can alternatively just mention it somewhere in the docs?

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 67.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
  npmPackages:
    minze: ^1.0.2 => 1.0.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/n6ai/minze/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/n6ai/minze/blob/main/.github/CONTRIBUTING.md).
- [X] Read the [docs](https://minze.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/n6ai/minze/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/n6ai/minze/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sergejcodes** [comment]
Most current Node versions are 16 and 18, it's probably better to bump the required Node version and update/mention it in the docs.
